services:
  - type: web
    name: sistema-cofii
    runtime: python
    pythonVersion: 3.11.8
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: sh -c "python scripts/init_db.py && gunicorn --bind 0.0.0.0:$PORT run:app"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
