services:
  - type: web
    name: sistema-cofii
    env: python
    pythonVersion: 3.11.8
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: sh -c "python scripts/init_db.py && gunicorn run:app"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
